### ISSUE TITLE
document and recommend usage of send_command() instead of call() for ioredis

### ISSUE THREAD

**Issue by MayaLi** [express-rate-limit/rate-limit-redis#113]
### Description

In the README for `ioredis` usage, the function `call()` is used to implement `sendCommand` as the following. B/c of the non-present type for the `call` function, a `@ts-expect-error` is used. 

```
// Redis store configuration
  store: new RedisStore({
    // @ts-expect-error - Known issue: the `call` function is not present in @types/ioredis
    sendCommand: (...args: string[]) => client.call(...args),
  }),
```

`ioredis` has another function `send_command` which seems to do just what you are looking for and is supported by @types/ioredis. The usage would look like the following
```
   sendCommand: (...args) => {
      const [command, ...commandArgs] = args;
      return client.send_command(command, ...commandArgs);
    },
```

Would you recommend the use of `send_command()` in the README? 

### Why

The `call()` function is not supported by @types/redis while `send_command()` is supported. It is much more intuitive to use. 

### Alternatives

The alternative is to continue using `call()` with the @ts-expect-error tag while unable to actually get first-class support in the IDE's.

**Comment by gamemaker1** [comment]
Hi,

Sorry I missed this! Thank you, will update the docs to use `send_command` instead.
