### ISSUE TITLE
Unable to handle connection loss

### ISSUE THREAD

**Issue by PaulAtST** [express-rate-limit/rate-limit-redis#166]
### Description

If my express server loses connection to my Redis server rate-limit-redis throws an exception which crashes my server. 

I tried adding error handling to my sendCommand callback function but I was unable to find a solution that satisfies the library. After looking at the library code a bit I think the library will need to be updated to better handle errors. 

It would be nice for the server not to crash and for the request to just be denied or allowed based on a fallback setting, when connection to Redis fails. In my case if Redis was down I would prefer to allow all request in temporally, but I can see why other would rather block all request.

Side note, it could be helpful if there was a an option in the future to fallback to an in memory store when Redis is down, this way the API can't be totally abused. 

### Library version

3.0.2

### Node version

v16.13.0

### Module system

CommonJS

### Redis Client

redis 4.6.7

**Comment by PaulAtST** [comment]
Yes this is still relevant. I also have learned that this was basically the behavior of redis rate limit 2, and has broken with Redis rate limit 3.

**Comment by gamemaker1** [comment]
Hi!

Apologies for the delay; this should be fixed in [v3.1.0](https://github.com/express-rate-limit/rate-limit-redis/releases/tag/v3.1.0).
