### ISSUE TITLE
Cannot install rate-limit-redis 3.1.0 with express-rate-limit 7.0.0

### ISSUE THREAD

**Issue by k0dard** [express-rate-limit/rate-limit-redis#194]
### Description

I've installed latest version (7.0.0) of express-rate-limit and wanted to add Redis store. However, when I tried  to install latest rate-limit-redis I got following error:
```
npm ERR! Found: express-rate-limit@7.0.0
npm ERR! node_modules/express-rate-limit
npm ERR!   express-rate-limit@"^7.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer express-rate-limit@"^6" from rate-limit-redis@3.1.0
npm ERR! node_modules/rate-limit-redis
npm ERR!   rate-limit-redis@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

### Library version

3.1.0

### Node version

v18.16.0

### Module system

CommonJS

**Comment by gamemaker1** [comment]
Hi,

Thanks for reporting the issue.

Could you please use the `--legacy-peer-deps` flag for now, while I release a version with `peerDeps` set to `>= 6`?

Thanks!

**Comment by k0dard** [comment]
That was fast, thanks a lot!
