### ISSUE TITLE
Invalid node version in documentation

### ISSUE THREAD

**Issue by LobovVitaliy** [express-rate-limit/rate-limit-redis#198]
### Description

<img width="749" alt="image" src="https://github.com/express-rate-limit/rate-limit-redis/assets/14150731/337a6fb7-de7e-4c59-99ca-1c3e117f1927">
<img width="214" alt="image" src="https://github.com/express-rate-limit/rate-limit-redis/assets/14150731/52b3b9ee-974f-4516-bdcb-f0f9cc334a87">

In node v14 there is a problem due to replaceAll

### Library version

4.1.2

### Node version

v14

### Module system

ESM

**Comment by gamemaker1** [comment]
Hi,

Thanks for reporting this, I'll fix it right away.
